name: Build EXE with PyInstaller

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile mastermind.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: mastermind-exe
        path: dist/mastermind.exe
